### ISSUE TITLE
Create Answer Model's `CRUD` services

### ISSUE THREAD

**Issue by Jasurbek1223** [sulton-max/Training.TestGorilla.Clone#35]
Description
Create Answer Model and `CRUD` Services

Requirements
Create AnswervModel with Crud Service

Deliverables
must Create models `CRUD` and `Interface`

**Comment by david-ae** [comment]
Please what is AnswervModel?

**Comment by Jasurbek1223** [comment]
We are creating a clone version of TestGorilla.com and therefore we need a Answer model
